---
- name: Provision kiosk to run podman applications
  hosts: all
  vars:
    systemd_units_dir: "/etc/systemd/system/"
    service_name: "inductive-automation-ignition"
    container_state: "installed"
    container_image: "docker.io/inductiveautomation/ignition"
    container_tag: "8.1"
    container_port_mapping: "8088:8088"
    container_extra_params: "--privileged -e GATEWAY_ADMIN_PASSWORD=redhat"

  roles:
    - kiosk_mode
    - container_lifecycle
