---

- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Allocate subuids for user
  subuid:
    user: "{{ ansible_user }}"
  become: true
  register: subuids

- name: Allocate subgids for user
  subgid:
    group: "{{ ansible_user }}"
  become: true
  register: subgids

- name: Ensure changes are applied to podman
  ansible.builtin.command: podman system migrate
  when: subuids is changed or subgids is changed

- name: Enable lingering for {{ ansible_user }}
  ansible.builtin.shell:
    cmd: loginctl enable-linger {{ ansible_user }}
  args:
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"

- name: Push out yaml
  ansible.builtin.template:
    src: templates/process-control.yml.j2
    dest: "/home/{{ ansible_user }}/process-control.yml"

- name: Podman play kube
  containers.podman.podman_play:
    kube_file: "/home/{{ ansible_user }}/process-control.yml"
    state: started
  register: app_deployed

- name: Wait for app startup
  ansible.builtin.wait_for:
    port: 1881
  when:
    - app_deployed.changed

- name: Allow 1881 through the firewall
  ansible.posix.firewalld:
    port: 1881/tcp
    zone: public
    permanent: true
    state: enabled
    immediate: true

- name: Print webui
  ansible.builtin.debug:
    msg: "http://{{ ipaddr }}:1881"
